apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: carvel-workshop
spec:
  vendor: learningcenter.tanzu.vmware.com
  title: Getting started with Carvel
  description: This workshop guides you through working with Carvel simple and composable tools for application deployment.
  difficulty: beginner
  duration: 120m
  url: https://github.com/bijoych/lab-getting-started-with-carvel
  content:
    image: gcr.io/cso-education-bchoudhury/carvel-workshop@sha256:e7da661e36b7b2d2b2947ffb344b8f3d198732ab7ef812722a295abbb514da65
    files: "github.com/bijoych/lab-getting-started-with-carvel?ref=master"
  session:
    budget: small
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true



